version: "3.8"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ejemplo_db
      TZ: America/New_York
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      TZ: America/New_York
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - db_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  postgres_data:

networks:
  db_net: