version: "3.9"

services:
  cuaspud:
    image: cuaspud:1.0.1
    build: .
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.cuaspud.entrypoints=http"
        - "traefik.http.routers.cuaspud.rule=Host(`cuaspud.byronrm.com`)"
        - "traefik.http.middlewares.cuaspud-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.cuaspud.middlewares=cuaspud-https-redirect"
        - "traefik.http.routers.cuaspud-secure.entrypoints=https"
        - "traefik.http.routers.cuaspud-secure.rule=Host(`cuaspud.byronrm.com`)"
        - "traefik.http.routers.cuaspud-secure.tls=true"
        - "traefik.http.routers.cuaspud-secure.tls.certresolver=http"
        - "traefik.http.routers.cuaspud-secure.service=cuaspud"
        - "traefik.http.services.cuaspud.loadbalancer.server.port=2407"
        - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true